enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("bronquitis",["moco_bronquial","fiebre"]).
enfe("enfisema",["fiebre","tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("bronquitis",["moco_bronquial","fiebre"]).
enfe("enfisema",["fiebre","tos","hiperinflacion"]).
enfe("gripa",["tos","moco"]).
enfe("tosferina",["fiebre","tos"]).
enfe("anemia",["fiebre","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("bronquitis",["moco_bronquial","fiebre"]).
enfe("enfisema",["fiebre","tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("bronquitis",["moco_bronquial","fiebre"]).
enfe("enfisema",["fiebre","tos","hiperinflacion"]).
enfe("gripa",["tos","moco"]).
enfe("tosferina",["fiebre","tos"]).
enfe("gripe",["tos","moco"]).
enfe("anemia",["fiebre","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("disnea",["tos","hiperinflacion"]).
enfe("bronquitis",["moco_bronquial","fiebre"]).
enfe("enfisema",["fiebre","tos","hiperinflacion"]).
enfe("gripe",["tos","moco"]).
enfe("asma",["moco_bronquial","tos"]).
enfe("gripe",["tos","moco"]).
